<?xml version="1.0"?>

<robot name="scooter" xmlns:xacro="https://www.ros.org/wiki/xacro">

    <material name='black'>
        <color rgba="0 0 0 0.8"/>
    </material>
    <material name='gray'>
        <color rgba="0.4 0.4 0.4 0.7"/>
    </material>
    <material name='blue'>
        <color rgba="0 0 0.8 0.7"/>
    </material>

    <xacro:property name="rad_front_wheel" value="${0.216/2}" />
    <xacro:property name="thick_wheel" value="0.044" />
    <xacro:property name="thick_steering" value="0.02" />

    <!-- base_link -->    
    <link name="base_link"/>

    <!-- steering_link -->
    <xacro:property name="alpha" value="${80 * pi / 180}" />
    <xacro:property name="steering_length" value="${0.2}" />


    <link name="steering_link">
        <visual>
            <geometry>
                <cylinder radius="${thick_steering}" length="${steering_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name='blue'/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${thick_steering}" length="${steering_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>           
        </collision>
    </link>

        <joint name="front_wheel_to_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="steering_link"/>
            <origin xyz="-${(steering_length/2 * cos(alpha))} 0.0 ${(steering_length/2 * sin(alpha)) + rad_front_wheel}" rpy="0.0 -${pi/2 - alpha} 0.0"/>
            <limit lower="-${pi/4}" upper="${pi/4}" effort="0.0" velocity="0.0"/>
            <axis xyz="0 0 1"/>
        </joint>


    <!-- front wheel -->
    <link name="front_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${thick_wheel}" radius="${rad_front_wheel}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <material name='black'/>
        </visual>
        
        <collision>
            <geometry>
                <cylinder length="${thick_wheel}" radius="${rad_front_wheel}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>           
        </collision>
    </link>

        <joint name="base_to_front_joint" type="continuous">
            <parent link="steering_link"/>
            <child link="front_wheel_link"/>
            <origin xyz="0.0 0.0 -${steering_length/2}" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 1 0"/>
        </joint>



    <!-- frame_link -->

    <xacro:property name="scale" value="${0.01}" />

    <link name="frame_link">
        <visual>
        <geometry>
            <mesh filename="package://scooter/description/meshes/frame.stl" scale="${scale} ${scale} ${scale}"/>
        </geometry>
        <material name='black'/>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} ${2* pi/180} ${pi}"/>
        </visual>

    </link>

    <joint name="base_to_frame_joint" type="fixed">
        <parent link="base_link"/>
        <child link="frame_link"/>
        <origin xyz="-0.728 0.0 0.109" rpy="0.0 0.0 0.0"/>
    </joint>



    <!-- back axis -->
    <xacro:property name="length_back_axis" value="0.3" />
    <xacro:property name="rad_back_wheel" value="${0.203/2}" />

    <link name="axis_link">
        <visual>
            <geometry>
                <cylinder radius="0.008" length="${length_back_axis}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <material name='gray'/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="0.01" length="${length_back_axis}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
    </link>

        <joint name="axis_joint" type="fixed">
            <parent link="frame_link"/>
            <child link="axis_link"/>
            <origin xyz="-0.14 0.0 -0.008" rpy="0.0 0.0 0.0"/>
        </joint>



    <!-- back wheel left -->

    <link name="back_wheel_left_link">
        <visual>
            <geometry>
                <cylinder length="${thick_wheel}" radius="${rad_back_wheel}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name='black'/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${thick_wheel}" radius="${rad_back_wheel}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
    </link>

        <joint name="base_to_back_left_joint" type="continuous">
            <parent link="axis_link"/>
            <child link="back_wheel_left_link"/>
            <origin xyz="0 ${length_back_axis/2} 0.0" rpy="${pi/2} 0.0 0.0"/>
            <axis xyz="0 0 1"/>
        </joint>

    <!-- back wheel right -->
    <link name="back_wheel_right_link">
        <visual>
            <geometry>
                <cylinder length="${thick_wheel}" radius="${rad_back_wheel}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name='black'/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${thick_wheel}" radius="${rad_back_wheel}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>            
        </collision>

    </link>

        <joint name="base_to_back_right_joint" type="continuous">
            <parent link="axis_link"/>
            <child link="back_wheel_right_link"/>
            <origin xyz="0.0 -${length_back_axis / 2} 0.0" rpy="${pi/2} 0.0 0.0"/>
            <axis xyz="0 0 1"/>
        </joint>

</robot>